### PR TITLE
basic crazy monkey ai

### PR DESCRIPTION
**Pull request by samachr**

### CODE REVIEW

**Comment by zcase** [comment]
This looks good to me. The next person should review and merge.

**Comment by KeskiDev** [comment]
Looks like the problem is the old UI stuff with the AI that is making it so we can't merge it.

**Comment by samachr** [comment]
Yeah, I noticed that. If you all approve of the changes I'll pull it down
and merge them in by hand.

**Comment by zcase** [comment]
Yea if you write in your AI logic with the current master code I feel it shall work really well. The AI concept works but there were error with the old stuff. So go ahead.

**Comment by KeskiDev** [comment]
I agree, the AI works well we just need to update the UI. Thumbs up to move forward.

**Pull request merged**
